### PR TITLE
bundles

### PR DESCRIPTION
**Pull request by SMOLKEYS**
""""many"""" changes

### CODE REVIEW

**Comment by SMOLKEYS** [comment]
what if i make bundles-unity

**Comment by Xeloboyo** [comment]
D: noo my goofy descriptions

**Comment by SMOLKEYS** [comment]
> D: noo my goofy descriptions

trolled

**Comment by Xeloboyo** [comment]
Ill accept if ya do the envrionment tiles as well :D

**Comment by SMOLKEYS** [comment]
> Ill accept if ya do the envrionment tiles as well :D

o no

it seems i must

**t r a n s c e n d   into the   e  d  i  t  o  e  r**

in order to obtain ***KNOWLEDGE***

of the **T         I           L            E            S**

**Comment by SMOLKEYS** [comment]
but

it will have to wait for approximately

# **2**

**Comment by SMOLKEYS** [comment]
and □□○●○○♤♡♤●♧ vash.acdeseconds

**Comment by Xeloboyo** [comment]
just did the environment stuff myself

**Comment by SMOLKEYS** [comment]
amogus

**Pull request merged**
