### PR TITLE
Torgue Wall Drill line recolour & Drive Shaft without arrow

### PR DESCRIPTION
**Pull request by xStaBUx**
Delete arrow from placing mode on Drive Shaft:
зображення
Line recolour on Wall Drill:

- yellow - will drill
- gray - won't do anything

> earlier: _red - "can`t"_
> now: _gray - "just nothing"_

javaw_XDRmgFTMaz

### CODE REVIEW

**Comment by Thesussy** [comment]
Nice

**Comment by Xeloboyo** [comment]
A 2 line change, fair enough.

**Comment by Thesussy** [comment]
Understood

**Comment by Thesussy** [comment]
ok so PU is not ported to 137, but for the mindustry builds

**Comment by xStaBUx** [comment]
> ok so PU is not ported to 137, but for the mindustry builds
i can do very small edit:
зображення

**Comment by Thesussy** [comment]
thx

**Pull request merged**
