### PR TITLE
Youngcha-Power-Generator(Pull request)

### PR DESCRIPTION
**Pull request by xStaBUx**
javaw_0dRtw1uptq
javaw_jGhOI0nkKi

> Energy generator for Youngcha faction.
> Needs torque
> Efficiency of energy production depends on torque

### CODE REVIEW

**Comment by code-explorer786** [comment]
nice!

**Comment by EclipseTheOldOne** [comment]
the community are doing the

**Comment by lokyinng** [comment]
look nice but for early v7 or late v7?

**Comment by xStaBUx** [comment]
> look nice but for early v7 or late v7?

late v7

**Comment by Thesussy** [comment]
nice...

**Comment by Thesussy** [comment]
make it playable on 136.1

**Comment by xStaBUx** [comment]
@Thesussy it playable on 136.1

**Comment by Thesussy** [comment]
Also can you fix bugs from issues category

**Comment by xStaBUx** [comment]
Hammm

**Pull request merged**
