### PR TITLE
Erekir port

### PR DESCRIPTION
**Pull request by Xeloboyo**
Most of the issues are fixed? Stable enough to merge back to master probably.

### CODE REVIEW

**Comment by BlueWolf3682** [comment]
i will return after some hours (i am going to run the mod through its paces to see if it crashes with anything)

**Comment by MEEPofFaith** [comment]
(Should the mod be updated to latest BE again in the case we want to use the new sounds?)

**Comment by Anuken** [comment]
@MEEPofFaith There's a regular-ish release schedule now, unless it's very important you should generally wait for releases instead of trying to use BE.

**Comment by MEEPofFaith** [comment]
i see

**Comment by Xeloboyo** [comment]
All good? :O

**Comment by Xeloboyo** [comment]
deaht

**Comment by MEEPofFaith** [comment]
daethh

**Pull request merged**
